### ISSUE TITLE
Nginx Extras failing with Passenger Enterprise

### ISSUE THREAD

**Issue by alikhan-io** [phusion/passenger-docker#152]
Currently my build breaks when trying to install nginx extras

```

The following packages have unmet dependencies:
 nginx-extras : Depends: perlapi-5.18.2 but it is not installable
                Depends: libperl5.18 (>= 5.18.2) but it is not installable
                Recommends: passenger-enterprise (< 5.0.31) but 1:5.0.30-2~trusty1 is to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" passenger-enterprise nginx-extra
```

Not sure why this is happening all of a sudden. Below is the docker file setup (My download token is sanitized)

```
FROM phusion/passenger-ruby23:latest
MAINTAINER Ali Khan "blah@example.com"
ADD passenger-enterprise-license /etc/passenger-enterprise-license

RUN echo deb https://download:$OURDOWNLOADTOKEN@www.phusionpassenger.com/enterprise_apt trusty main > /etc/apt/sources.list.d/passenger.list

RUN apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" passenger-enterprise nginx-extras
```

It seems like the incorrect passenger is being downloaded but I'm not sure why as we're updating the sources with passenger.

**Comment by steti** [comment]
It looks like this image has been updated to be based on Ubuntu Xenial (16.04) instead of Trusty (14.04), so you need to update your apt source.

Change

`RUN echo deb https://download:$OURDOWNLOADTOKEN@www.phusionpassenger.com/enterprise_apt trusty main > /etc/apt/sources.list.d/passenger.list`

to

`RUN echo deb https://download:$OURDOWNLOADTOKEN@www.phusionpassenger.com/enterprise_apt xenial main > /etc/apt/sources.list.d/passenger.list`

and you should be good.

The README.md file in this repo was updated to reflect this (some time after this question was asked).

**Comment by FooBarWidget** [comment]
The README has since been fixed.
