### ISSUE TITLE
syslog spam

### ISSUE THREAD

**Issue by phortx** [phusion/passenger-docker#165]
If I setup a Jelastic (4.9.2) docker environment with the `passenger-full` image as application server container, the container spams the `/var/log/syslog` until the container storage is full, but without an useful error message or a message at all, just the hostname of the environment:

**/var/log/syslog**
```
Jan  9 14:17:32 node14xxxx-container-host-name runsvdir-start[295]: Jan  9 14:17:29 node14xxxx-container-host-name runsvdir-start[295]: Jan  9 14:17:26 node14xxxx-container-host-name runsvdir-start[295]: Jan  9 14:17:23 node14xxxx-container-host-name runsvdir-start[295]: node14xxxx-container-host-name runsvdir-start[295]: Jan  9 14:16:52 node14xxxx-container-host-name
```

That also happens with the `phusion/passenger-ruby23` image.

Does anyone have any idea why this is happening?

**Comment by leifcr** [comment]
@phortx I haven't seen this on the passenger-full image, however the issue is likely to be related to a service that doesn't start up properly with runit.

Runit will attempt to restart the service that fails until it is manually stopped or as you experience, storage ends up full.

One way to delay and limit runit restarting the service is by implementing start/finish scripts similar to this:
https://github.com/leifcr/capistrano-puma/blob/master/templates/runit/run.erb
https://github.com/leifcr/capistrano-puma/blob/master/templates/runit/finish.erb

I suggest looking at redis, memcached and nginx logs to see if one of the services crashes/stops.

**Comment by OnixGH** [comment]
@phortx do you have any updates? Does this issue occur for you with a clean `passenger-full` container?

**Comment by phortx** [comment]
I don't have the passenger installation anymore, so I can't say anything further to that issue. I think we should close that, as long as nobody else has any troubles like that :)

**Comment by OnixGH** [comment]
@phortx Ok, thanks. We can always reopen if we get more info that there's an issue with the image.
