### ISSUE TITLE
web application could not be started 

### ISSUE THREAD

**Issue by dnsslzr** [phusion/passenger-docker#217]
![screen shot 2018-05-07 at 10 18 10 am](https://user-images.githubusercontent.com/39060195/39709611-f7c34660-51df-11e8-88fb-8e1b1ddaff26.png)

Hello everyone, I hope you can help me, anyone can enter the domain, but when trying to enter from the network of the company I have this error, could you help me please?

**Comment by OnixGH** [comment]
Hi, Passenger is an open source server for web apps that anyone can use. You should contact the network / application administrator of www.gavacapital.com who are responsible for this site.

**Comment by dnsslzr** [comment]
Thank you very much for your response and what would I have to do? neither the network provider nor the web developers know what to do = (

**Comment by OnixGH** [comment]
Information about setting up Passenger correctly can be found in the [documentation](https://www.phusionpassenger.com/library/).

For more help you can always try the passenger tag on [Stack Overflow](https://stackoverflow.com/questions/tagged/passenger). If you're sure the problem is not with the application but with Passenger then the best place to report is at the [Passenger issue tracker](https://github.com/phusion/passenger/issues) (making sure to fill out the questions).
