### ISSUE TITLE
Bitbucket pipelines and multi-stage builds

### ISSUE THREAD

**Issue by trueinviso** [phusion/passenger-docker#235]
I am using Bitbucket pipelines to build my Docker images and this is my base image.  During my build I have to use a secret key to build the image i.e.:

``` 
ARG SEKRETS_KEY 
WORKDIR "/home/app"
RUN echo "$SEKRETS_KEY" > .sekrets.key 
...
RUN rm .sekrets.key  
```

I want to remove the layer that has the secret key from the final image.  Bitbucket pipelines doesn't support Docker experimental features so I can't use `--squash`.  Their team recommends using multi-stage builds.  I set up my Dockerfile to use multi-stage builds like so:

```
FROM phusion/passenger-ruby23 AS build
...
ARG SEKRETS_KEY 
WORKDIR "/home/app"
RUN echo "$SEKRETS_KEY" > .sekrets.key 
...
RUN rm .sekrets.key
FROM phusion/passenger-ruby23
...
COPY --from=build /home/app /home/app
```

However this throws an error on Bitbucket:

```failed to copy files: failed to copy directory: Error processing tar file(exit status 1): Container ID 175535 cannot be mapped to a host ID```

After researching this error with Bitbucket it appears that the issue lies with the base image.  The official answer can be [found at this link:](https://bitbucket.org/site/master/issues/17319/docker-builds-started-failing-with)

## Builds fails due to error: “Container ID Cannot Be Mapped to Host ID Error”

Due to the way userns remap works (by remapping UID/GIDs to another less privileged UID/GID in the hosts namespace), UID/GIDs that are placed on files must be in the range 0-65535.

If you recieve this error, you will need to perform a fix on the image that has this invalid UID/GID.

If your recieved this error against a file that you created and placed into an image, the fix is to simply change the UID/GID of the file to one within the range.

To find the file, first get the invalid UID/GID from the error message and run the following command on the files within the container.

`find / -uid|-gid <invalid-uid-or-guid> -ls`

To fix the ownership of the file use the following command

`chown -R UID_IN_RANGE:GID_IN_RANGE filename`

```If you received this error against a file that was already present in a layer of the base image you depend on, you will need to raise a support case and work with the image maintainers of the base image to get this resolved.```

Apparently this issue is caused by limitations of enabling docker user namespace remap.

**Comment by ludwick** [comment]
We use passenger phusion docker as a base image in our second stage with succes on BB Pipelines. But, we don't use it as the base for the first stage. Depending on what you need to do in the first stage, you might consider a different base image (we happen to use ubuntu due to toolchains being convenient) for that first stage, which might help avoid this with less complexity.

**Comment by eidast** [comment]
An option to avoid this issue is, make all files own to root in the build stahe and then in the last stage of the container fix the user property.

An example at following:

`#########
# BUILD #
#########

# base image
FROM jekyll/builder AS build

WORKDIR /app
COPY . /app

RUN chmod a+w Gemfile.lock && \
    bundle install
RUN jekyll build && \ 
    chown -R root:root *

##########
# STATIC #
##########

FROM nginx:latest

COPY --from=build /app/_site/ /usr/share/nginx/html/
RUN chown -R nginx.nginx /usr/share/nginx/html/*

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]`

**Comment by CamJN** [comment]
Closing as a workaround was provided.
