### ISSUE TITLE
Error on syslog-ng.init causing container not to start

### ISSUE THREAD

**Issue by dmp1ce** [phusion/passenger-docker#257]
I'm not sure if this is related to phusion/baseimage-docker#525 but I'm getting the following error on the most recent `phusion/passenger-ruby23` image. Arch Linux host. Docker version: `18.09.5-ce`.

```
passenger_1     | *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
passenger_1     | *** Running /etc/my_init.d/10_syslog-ng.init...
passenger_1     | [2019-05-11T18:27:40.329161] Error opening control socket, bind() failed; socket='/var/lib/syslog-ng/syslog-ng.ctl', error='Permission denied (13)'
passenger_1     | May 11 18:27:40 a11679c47c41 syslog-ng[21]: syslog-ng starting up; version='3.13.2'
passenger_1     | *** /etc/my_init.d/10_syslog-ng.init failed with status 1
passenger_1     | *** Killing all processes...
passenger_1     | May 11 18:28:10 a11679c47c41 syslog-ng[21]: syslog-ng shutting down; version='3.13.2'
```

This error seems to block the container for continuing causing my application to not function with new builds.

**Comment by CamJN** [comment]
Closing as stale, but it doesn't seem to effect the current images in my testing.

**Comment by hitesh-goel** [comment]
@dmp1ce were you able to resolve this issue?

**Comment by CamJN** [comment]
@hitesh-goel this is a different issue from #347

**Comment by dmp1ce** [comment]
@hitesh-goel I don't know. I'm not using most of those containers anymore. There seem to be several :+1: on the issue though.

**Comment by mathieujobin** [comment]
@dmp1ce There was not enough information provided to troubleshoot the issue anyway.

You had to look up the syslog-ng log inside docker.

Also, I hope you are no longer using ruby 2.3; 2.6 is already deprecated.

personally, I use `passenger-ruby` not `passenger-docker` but I guess they are very similar.
I removed syslog-ng and I am using rsyslog to push my logs to loggly, maybe that's why I never had this problem.
