### ISSUE TITLE
add to README: tip for running `/sbin/my_init` manually and debugging (from baseimage-docker README)

### ISSUE THREAD

**Issue by hangtwenty** [phusion/passenger-docker#56]
The baseimage-docker README makes it fairly clear that one can do things like the following, to debug when your `/sbin/my_init` is a dud (because you put bad scripts, etc.):
- `docker run --rm -t -i phusion/baseimage:<VERSION> /sbin/my_init -- bash -l` ([here](https://github.com/phusion/baseimage-docker#inspecting-baseimage-docker))
- `docker run -t -i <YOUR_NAME_IMAGE> /sbin/my_init -- bash -l` ([here](https://github.com/phusion/baseimage-docker))

So in my use case, using `passenger-docker` base image and administering it with `fig`, I've learned I can do: 
- `fig run web /sbin/my_init`

to get at my problems in my `web` container. This is extremely helpful and before I realized I could do this, I was puzzled as to how to debug `/sbin/my_init` (because nothing winds up in `syslog` if you've completely borked it). 

It will probably save some newbies (like me!) some trouble if the passenger-docker README also provides this suggestion for debugging.

**Comment by OnixGH** [comment]
This was posted to the wrong tracker (phusion/passenger-docker instead of phusion/baseimage-docker).

Either way it's been a while and Fig is deprecated, replaced by [Docker Compose](https://docs.docker.com/compose/). With the increased ecosystem maturity I don't think we need to go into this further.
