### ISSUE TITLE
Code reloading in development mode?

### ISSUE THREAD

**Issue by cheeyeo** [phusion/passenger-docker#58]
Am I right in saying that passenger supports code reloading in development mode by setting the passenger_app_env to development?

I tried seeing passenger_app_env to development for a rails app running in a docker container but the code reload does not happen?

Am i missing a step?

thanks

chee

**Comment by agilgur5** [comment]
Is `PASSENGER_APP_ENV` supposed to enable code reloading in Python apps (i.e. Django) as well? There doesn't seem to be any documentation on this in the repo and I've been scouring the web to try to figure out how to enable it to no avail...

**Comment by FooBarWidget** [comment]
No. `PASSENGER_APP_ENV` is just an environment variable. If Django supports code reloading then you have to find some way to enable that based on the `PASSENGER_APP_ENV` environment variable.

**Comment by agilgur5** [comment]
Interesting... so `PASSENGER_APP_ENV` doesn't do anything on its own? Or it only does something for Rails?

I had assumed that `PASSENGER_APP_ENV=development` would start some runit process that would watch for file changes and run `passenger-config restart-app` when detected, as that would work as a universal hot code reloader not tied to a specific framework or language (so long as you configured it to work with Passenger, which is a prerequisite in using this container properly)

**Comment by FooBarWidget** [comment]
In addition to setting `PASSENGER_APP_ENV`, we also set `RAILS_ENV`, `RACK_ENV` and `NODE_ENV`. Rails respects `RAILS_ENV`.

For all frameworks that don't support at least one of those variables, you'll have to take care of that yourself.

Maybe you'd be interested in the `always_restart.txt` mechanism which is good for code reloading when using a framework that doesn't support it: https://www.phusionpassenger.com/library/walkthroughs/basics/python/reloading_code.html#tmp-always_restart-txt

**Comment by agilgur5** [comment]
Gotcha, thanks @FooBarWidget!!

I wasn't sure about `always_restart.txt` since it restarts on _each request_, but it seems to have no significant impact on load time for my Django app!

I'd love it if Passenger had the more advanced approach of restarting only when files changed as I proposed above (using something like [listen](https://github.com/guard/listen)), which `passenger-docker` could auto-run as proposed above as a framework agnostic solution. I could work on this feature, but considering PRs don't seem to get responded to with any frequency in this repo (including one of my own), not sure what the point would be if it doesn't get merged...

**Comment by abderraxim** [comment]
https://www.phusionpassenger.com/library/walkthroughs/basics/python/reloading_code.html#tmp-always_restart-txt
