### ISSUE TITLE
passenger-full contains Node.js 0.10 instead of 0.12

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger-docker#96]
It is said that passenger-full contains Node.js 0.10 instead of 0.12. We should investigate and fix this.

**Comment by blakmatrix** [comment]
Node 0.10 is still better for production apps and most likely will continue to be so until LTS is out (last I heard that would be when io.js reaches 3.x or 4.x in the next few months)

**Comment by FooBarWidget** [comment]
0.10 is better for production apps? Why is that? 0.12 has been out for a while now, is part of the stable branch, and I'm not aware of any stability or compatibility issues.

**Comment by blakmatrix** [comment]
Forgive me, my comment was based on anecdotal evidence and conversations with engineers and thier comments on what they are using at thier jobs and why, overwhelmingly it seems like the only people using 0.12 or io.js for its latest features and things like ES6 support, of the people I've surveyed this is only about 5% while many are still on 0.10.x waiting for LTS before investing in the effort of an upgrade.

I personally tried upgrading to 0.12 stable, and had too many issues(mostly library issues) to continue the migration. Since then I've been surveying people in the node community to find the right time to tackle upgrading again. Its been well over 6 months, but I am still hearing the majority of production apps seem to be running on 0.10 with expected upgrades around LTS release. 

My suggestion is if you do upgrade to 0.12, leave a way for people to easily use 0.10 as well at least until LTS is out.

**Comment by FooBarWidget** [comment]
I'm afraid there isn't a good way for people to use 0.10. We use the NodeSource APT repo so we can only install 0.12. People will have to use older passenger-docker releases if they wish to stay on 0.10.

Alternatively I could look into using Chris Lea's PPA, which is still on 0.10. But I'd like to hear more comments from the community about whether having a separate Node.js 0.10 variant is desirable.

**Comment by rwky** [comment]
I use 0.12 in production without any problems. I also maintain ppas for 0.10 and 0.12 
https://launchpad.net/~rwky/+archive/ubuntu/nodejs-legacy
https://launchpad.net/~rwky/+archive/ubuntu/nodejs

Feel free to use them. I know they both work with the docker image since I use them in my own images based on phusion-passenger/customizable
